file.value = Datei
help.value = Hilfe
gamemode.value = Wähle deinen Spielmodus:
new.value = Neu
open.value = Öffnen
quit.value = Beenden
rules.value = Regeln
about.value = Über uns
pvp.value = Spieler gegen Spieler
pve.value = Spieler gegen Computer
eve.value = Computer gegen Computer
choosepvp.value = Du hast Spieler gegen Spieler gewählt, wähle nun die Namen der Teilnehmer
player1.value = Gib den Namen für Spieler 1 ein
player2.value = Gib den Namen für Spieler 2 ein
launch.value = Starten
choosepve.value = Du hast Spieler gegen Computer gewählt, wähle nun den Namen des Teilnehmers
chooseeve.value = Du hast Computer gegen Computer gewählt
coup.value = Gespielte Züge
