file = File
help = Help
gamemode = Choose your gamemode :
new = New
open = Open
quit = Quit
rules = Rules
about = About us
pvp = PvP
pve = PvC
eve = CvC
choosepvp = You choose Player Versus Player now choose the names of the participants
player1 = enter the name for the player 1
player2 = enter the name for the player 2
launch = launch
choosepve = You choose Player Versus Computer now choose the name of the participant
chooseeve = You choose Computer Versus Computer
coup = moves played

